# Generated by Django 4.1 on 2022-08-10 09:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phoneNum', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('mainFlower1_amount', models.IntegerField(null=True)),
                ('mainFlower2_amount', models.IntegerField(null=True)),
                ('mainFlower3_amount', models.IntegerField(null=True)),
                ('subFlower1_amount', models.IntegerField(null=True)),
                ('subFlower2_amount', models.IntegerField(null=True)),
                ('subFlower3_amount', models.IntegerField(null=True)),
                ('bunchOfFlowers1_amount', models.IntegerField(null=True)),
                ('bunchOfFlowers2_amount', models.IntegerField(null=True)),
                ('totalPrice', models.IntegerField(null=True)),
                ('bunchOfFlowers1_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bunchOfFlower1', to='seller.bunchofflowers')),
                ('bunchOfFlowers2_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bunchOfFlower2', to='seller.bunchofflowers')),
                ('mainFlower1_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainFlower1', to='seller.mainflower')),
                ('mainFlower2_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainFlower2', to='seller.mainflower')),
                ('mainFlower3_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainFlower3', to='seller.mainflower')),
                ('subFlower1_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subFlower1', to='seller.subflower')),
                ('subFlower2_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subFlower2', to='seller.subflower')),
                ('subFlower3_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subFlower3', to='seller.subflower')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpLocation',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('depart', models.CharField(max_length=150)),
                ('dest', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('requirement', models.TextField(null=True)),
                ('totalPrice', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('0', '결제 안됨'), ('1', '주문 수락'), ('2', '배송중'), ('3', '배송 완료')], default='0', max_length=10)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
