# Generated by Django 4.1 on 2022-08-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='status',
        ),
    ]
