# Generated by Django 4.0.6 on 2022-07-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('customer', '0002_alter_cart_bunchofflowers1_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bunchOfFlowers1_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bunchOfFlower1', to='seller.bunchofflowers'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bunchOfFlowers2_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bunchOfFlower2', to='seller.bunchofflowers'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower1_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainFlower1', to='seller.mainflower'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower2_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainFlower2', to='seller.mainflower'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mainFlower3_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainFlower3', to='seller.mainflower'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower1_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subFlower1', to='seller.subflower'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower2_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subFlower2', to='seller.subflower'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subFlower3_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subFlower3', to='seller.subflower'),
        ),
    ]
