# Generated by Django 4.1 on 2022-08-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_ordertable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bunchOfFlowers1_color',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='bunchOfFlowers2_color',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower1_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower2_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower3_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower1_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower2_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower3_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
