# Generated by Django 4.0.6 on 2022-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='idx',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
