# Generated by Django 4.0.3 on 2022-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_bunchofflowers1_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bunchOfFlowers1_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='bunchOfFlowers2_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower1_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower2_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower3_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shopname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower1_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower2_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower3_price',
            field=models.IntegerField(null=True),
        ),
    ]
