# Generated by Django 4.1 on 2022-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bunchOfFlowers1_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='bunchOfFlowers2_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower1_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower2_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mainFlower3_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shopname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower1_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower2_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='subFlower3_price',
            field=models.IntegerField(null=True),
        ),
    ]
