# Generated by Django 4.0.3 on 2022-09-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_cart_bunchofflowers1_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bunchOfFlowers1_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='bunchOfFlowers2_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='mainFlower1_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='mainFlower2_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='mainFlower3_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shopname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subFlower1_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subFlower2_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subFlower3_price',
        ),
    ]
