# Generated by Django 4.1 on 2022-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Deliver',
        ),
    ]
